export const eloETier = [
  { elo: "Ferro", tier: 4 },
  { elo: "Ferro", tier: 3 },
  { elo: "Ferro", tier: 2 },
  { elo: "Ferro", tier: 1 },
  { elo: "Bronze", tier: 4 },
  { elo: "Bronze", tier: 3 },
  { elo: "Bronze", tier: 2 },
  { elo: "Bronze", tier: 1 },
  { elo: "Prata", tier: 4 },
  { elo: "Prata", tier: 3 },
  { elo: "Prata", tier: 2 },
  { elo: "Prata", tier: 1 },
  { elo: "Ouro", tier: 4 },
  { elo: "Ouro", tier: 3 },
  { elo: "Ouro", tier: 2 },
  { elo: "Ouro", tier: 1 },
  { elo: "Platina", tier: 4 },
  { elo: "Platina", tier: 3 },
  { elo: "Platina", tier: 2 },
  { elo: "Platina", tier: 1 },
  { elo: "Diamante", tier: 4 },
  { elo: "Diamante", tier: 3 },
  { elo: "Diamante", tier: 2 },
  { elo: "Diamante", tier: 1 },
  { elo: "Mestre", tier: "" },
];
